global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'willy-wonka-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'willy-wonka-factory'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:7999']
        labels:
          application: 'willy-wonka-factory'
          environment: 'development'
    
